// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzynnbqppovzqhfqlgfd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6eW5uYnFwcG92enFoZnFsZ2ZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5NDc5ODgsImV4cCI6MjA2MzUyMzk4OH0.am55XAX3FPGUxLv_4cbEDSheuVSKWxrt_L4OUmSNIZ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);